### ISSUE TITLE
main_classification.py and main_segmentation.py

### ISSUE THREAD

**Issue by ZhangRan24** [jlianglab/Ark#3]
Thank you very much for your excellent work. May I ask if it is possible to release files that main_classification.py and main_segmentation.py.

**Comment by Mda233** [comment]
Hi, for main_classification.py, please refer to:
https://github.com/jlianglab/BenchmarkTransformers

**Comment by maxrohleder** [comment]
Thank you for the cool work. Would it be possible to get an example how to use this backbone in a segmentation task?

**Comment by Mda233** [comment]
Thanks for following our work! I’ve prepared a repo for the  segmentation tasks.
Please check: 
https://github.com/Mda233/BenchmarkTransformersSegmentation
